import { differenceInCalendarDays, isBefore, parseISO, startOfDay } from 'date-fns'
import type { Artwork, Material, Order, PrintState } from '../types/domain'

export const stageLabels = { briefing: 'Briefing / arte', approval: 'Aguardando aprovação', preparation: 'Preparação', production: 'Produção', finishing: 'Acabamento', ready: 'Pronto', installation: 'Instalação / entrega', completed: 'Finalizado' } as const
export const artworkLabels = { draft: 'Rascunho', sent: 'Enviada', changes: 'Alteração solicitada', approved: 'Aprovada' } as const
export function customerFor(state: PrintState, order: Order) { return state.customers.find((c) => c.id === order.customerId) }
export function artworkFor(state: PrintState, order: Order) { return state.artworks.find((a) => a.id === order.artworkId) }
export function responsibleFor(state: PrintState, order: Order) { return state.responsibles.find((r) => r.id === order.responsibleId) }
export function balance(order: Order) { return order.total - order.received }
export function available(material: Material) { return material.stock - material.reserved }
export function hasLowStock(material: Material) { return available(material) <= material.minimum }
export function isOverdue(order: Order) { return order.stage !== 'completed' && isBefore(parseISO(order.promisedDate), startOfDay(new Date())) }
export function isDueSoon(order: Order) { const diff = differenceInCalendarDays(parseISO(order.promisedDate), startOfDay(new Date())); return order.stage !== 'completed' && diff >= 0 && diff <= 2 }
export function needsApproval(order: Order, artwork?: Artwork) { return Boolean(order.artworkRequired && artwork && artwork.currentVersionId !== artwork.approvedVersionId) }
export function hasMaterialShortage(state: PrintState, order: Order) { return order.materialRequirements.some((req) => { const material = state.materials.find((m) => m.id === req.materialId); return !material || available(material) < Math.max(0, req.required - req.reserved) }) }
export function hasInstallationTomorrow(order: Order) { return order.deliveryInstallation.type === 'installation' && order.deliveryInstallation.scheduledDate && differenceInCalendarDays(parseISO(order.deliveryInstallation.scheduledDate), startOfDay(new Date())) === 1 }
export function getMetrics(state: PrintState) { const active = state.orders.filter((o) => o.stage !== 'completed'); return { active: active.length, waiting: active.filter((o) => needsApproval(o, artworkFor(state, o))).length, overdue: active.filter(isOverdue).length, installations: active.filter(hasInstallationTomorrow).length, openBalance: active.reduce((sum, o) => sum + balance(o), 0) } }
export function getAlerts(state: PrintState) { return state.orders.flatMap((order) => { const artwork = artworkFor(state, order); const items: { kind: string; title: string; detail: string; orderId: string; tone: string }[] = []; if (artwork?.status === 'changes') items.push({ kind: 'change', title: 'Alteração solicitada', detail: `#${order.orderNumber} · ${customerFor(state, order)?.companyName}`, orderId: order.id, tone: 'danger' }); else if (needsApproval(order, artwork)) items.push({ kind: 'approval', title: 'Arte aguardando aprovação', detail: `#${order.orderNumber} · ${order.serviceType}`, orderId: order.id, tone: 'warning' }); if (isOverdue(order)) items.push({ kind: 'overdue', title: 'Prazo vencido', detail: `#${order.orderNumber} · ${customerFor(state, order)?.companyName}`, orderId: order.id, tone: 'danger' }); if (hasInstallationTomorrow(order)) items.push({ kind: 'installation', title: 'Instalação amanhã', detail: `#${order.orderNumber} · ${order.deliveryInstallation.location}`, orderId: order.id, tone: 'blue' }); if (hasMaterialShortage(state, order)) items.push({ kind: 'material', title: 'Material insuficiente', detail: `#${order.orderNumber} · ${order.serviceType}`, orderId: order.id, tone: 'warning' }); return items }) }
