import { useState, type FormEvent } from 'react';
import { NavLink, Outlet, Route, Routes, useLocation, useNavigate, useOutletContext, useParams } from 'react-router-dom';
import { AlertTriangle, ArrowLeft, ArrowRight, Boxes, Check, ChevronRight, Clipboard, Factory, FileText, LayoutDashboard, Menu, PackagePlus, Palette, RotateCcw, Search, Settings, Shirt, Sparkles, Users, X } from 'lucide-react';
import { dayMonth, gridTotal, money, shortDate, sizes, type Order, type Priority, type SizeRow } from './domain';
import { readPersonalization } from './personalization';
import { clientStats, dashboardAlerts, dashboardKpis, daysFromNow, materialReserved, materialStatus, orderProgress } from './selectors';
import { useStore } from './store';

type ShellContext = { notify:(message:string)=>void };
const useShell = () => useOutletContext<ShellContext>();
const labelStatus = (value:string) => value.charAt(0).toUpperCase()+value.slice(1);
const greeting = () => new Date().getHours()<12?'Bom dia':new Date().getHours()<18?'Boa tarde':'Boa noite';

const nav = [
  { to:'/', label:'Visão geral', icon:LayoutDashboard, end:true }, { to:'/pedidos', label:'Pedidos', icon:Shirt }, { to:'/producao', label:'Produção', icon:Factory },
  { to:'/orcamentos', label:'Orçamentos', icon:FileText }, { to:'/clientes', label:'Clientes', icon:Users }, { to:'/estoque', label:'Materiais', icon:Boxes }, { to:'/configuracoes', label:'Ajustes da demo', icon:Settings },
];

export function App() {
  return <Routes><Route element={<Shell/>}>
    <Route index element={<Dashboard/>}/><Route path="pedidos" element={<Orders/>}/><Route path="pedidos/novo" element={<NewOrder/>}/><Route path="pedidos/:id" element={<OrderDetail/>}/>
    <Route path="producao" element={<Production/>}/><Route path="orcamentos" element={<Quotes/>}/><Route path="orcamentos/novo" element={<NewQuote/>}/><Route path="orcamentos/:id" element={<QuoteDetail/>}/>
    <Route path="clientes" element={<Clients/>}/><Route path="clientes/:id" element={<ClientDetail/>}/><Route path="estoque" element={<Inventory/>}/><Route path="configuracoes" element={<Configuration/>}/>
    <Route path="cliente/orcamento/:id" element={<CustomerPortal/>}/><Route path="*" element={<NotFound/>}/>
  </Route></Routes>;
}

function Shell() {
  const { state,storageError }=useStore(); const [menuOpen,setMenuOpen]=useState(false); const [toast,setToast]=useState(''); const [tour,setTour]=useState(false); const [tourStep,setTourStep]=useState(0);
  const custom=readPersonalization(); const color=custom.color??state.config.primaryColor; const demoName=custom.company??state.config.companyName;
  const location=useLocation(); const isPortal=location.pathname.startsWith('/cliente/');
  const notify=(message:string)=>{setToast(message); window.setTimeout(()=>setToast(''),2600)};
  if(isPortal) return <div style={{'--brand':color} as React.CSSProperties}><Outlet context={{notify}}/>{toast&&<div className="toast" role="status">{toast}</div>}</div>;
  return <div className="app-shell" style={{'--brand':color} as React.CSSProperties}>
    <aside className={`sidebar ${menuOpen?'open':''}`} aria-label="Navegação principal">
      <div className="brand"><span className="brand-mark">{state.config.logoText}</span><div><strong>{demoName}</strong><small>{custom.company?`Demonstração para ${custom.company}`:'Operação sob medida'}</small></div><button className="icon-button close-menu" onClick={()=>setMenuOpen(false)} aria-label="Fechar menu"><X size={20}/></button></div>
      <nav>{nav.map(item=><NavLink key={item.to} to={item.to} end={item.end} onClick={()=>setMenuOpen(false)}><item.icon size={18}/><span>{item.label}</span></NavLink>)}</nav>
      <div className="sidebar-footer"><button className="tour-link" onClick={()=>{setTourStep(0);setTour(true)}}><Sparkles size={17}/>Conhecer o sistema</button><p>{state.config.demoLabel}</p><small>Modelo demonstrativo. O sistema final pode ser adaptado ao processo da sua empresa.</small></div>
    </aside>
    {menuOpen&&<button className="scrim" onClick={()=>setMenuOpen(false)} aria-label="Fechar menu"/>}
    <main className="main"><header className="topbar"><button className="icon-button menu-button" onClick={()=>setMenuOpen(true)} aria-label="Abrir menu"><Menu/></button><div><span className="eyebrow">{custom.company?`Demonstração para ${custom.company}`:state.config.city}</span></div><div className="demo-pill">Ambiente de demonstração <span>• dados fictícios</span></div></header>{storageError&&<div className="storage-warning">A persistência local está indisponível. As alterações ficam nesta sessão.</div>}<div className="page"><Outlet context={{notify}}/></div></main>
    <nav className="bottom-nav" aria-label="Navegação móvel">{nav.slice(0,5).map(item=><NavLink key={item.to} to={item.to} end={item.end}><item.icon size={20}/><span>{item.label.split(' ')[0]}</span></NavLink>)}</nav>
    {toast&&<div className="toast" role="status" aria-live="polite"><Check size={18}/>{toast}</div>}
    {tour&&<Tour step={tourStep} onClose={()=>{setTour(false);localStorage.setItem('confec-demo:tour','done')}} onNext={()=>tourStep===5?setTour(false):setTourStep(step=>step+1)}/>} 
  </div>;
}

const tourCopy=[
  ['O que precisa da sua atenção','Riscos de prazo, aprovações e materiais aparecem primeiro, sempre ligados aos pedidos reais da demonstração.'],
  ['Pedidos e prazos juntos','Busque, filtre e abra qualquer pedido para ver produto, grade, materiais, valores e histórico.'],
  ['Produção visível','O quadro mostra onde cada pedido está. A etapa pode ser alterada também por toque e teclado.'],
  ['Tudo no mesmo pedido','Arte aprovada, grade, necessidades de materiais e ocorrências permanecem centralizadas.'],
  ['Aprovação pelo cliente','O portal demonstrativo atualiza o mesmo orçamento visto pela equipe administrativa.'],
  ['Adaptado à sua empresa','No sistema real, etapas, campos, regras e integrações podem acompanhar o processo que já funciona na operação.'],
];
function Tour({step,onClose,onNext}:{step:number;onClose:()=>void;onNext:()=>void}) { return <div className="modal-backdrop" role="dialog" aria-modal="true" aria-labelledby="tour-title"><div className="tour-card"><div className="tour-progress">{tourCopy.map((_,index)=><span key={index} className={index<=step?'active':''}/>)}</div><span className="eyebrow">Passo {step+1} de 6</span><h2 id="tour-title">{tourCopy[step][0]}</h2><p>{tourCopy[step][1]}</p><div className="actions"><button className="button ghost" onClick={onClose}>Fechar</button><button className="button primary" onClick={onNext}>{step===5?'Concluir':'Continuar'}<ArrowRight size={17}/></button></div></div></div> }

function PageHeader({eyebrow,title,description,action}:{eyebrow?:string;title:string;description?:string;action?:React.ReactNode}) { return <header className="page-header"><div>{eyebrow&&<span className="eyebrow">{eyebrow}</span>}<h1>{title}</h1>{description&&<p>{description}</p>}</div>{action}</header> }
function Kpi({label,value,detail}:{label:string;value:string|number;detail:string}) { return <div className="kpi"><span>{label}</span><strong>{value}</strong><small>{detail}</small></div> }
function StageChip({order}:{order:Order}) { const {state}=useStore(); return <span className="chip">{state.stages.find(stage=>stage.id===order.stageId)?.label}</span> }

function Dashboard() {
  const {state}=useStore(); const kpis=dashboardKpis(state); const alerts=dashboardAlerts(state); const navigate=useNavigate();
  const deliveries=[...state.orders].sort((a,b)=>a.deadline.localeCompare(b.deadline)).slice(0,5);
  return <><PageHeader eyebrow="Visão de hoje" title={`${greeting()}. Aqui está a produção de hoje.`} description="Uma leitura rápida do que está andando e do que pede decisão." action={<button className="button secondary" onClick={()=>navigate('/producao')}>Abrir produção<ArrowRight size={17}/></button>}/>
    <section className="kpi-grid" aria-label="Indicadores"><Kpi label="Pedidos em andamento" value={kpis.active} detail="em 7 etapas do fluxo"/><Kpi label="Peças em produção" value={kpis.pieces.toLocaleString('pt-BR')} detail="somadas dos pedidos ativos"/><Kpi label="Entregas próximas" value={kpis.upcoming} detail="nos próximos 5 dias"/><Kpi label="Dentro do prazo" value={`${kpis.onTime}%`} detail="dos pedidos em andamento"/></section>
    <section><div className="section-heading"><div><span className="eyebrow">Prioridade operacional</span><h2>Precisa da sua atenção</h2></div><small>{alerts.length} situações derivadas do estado atual</small></div><div className="attention-list">{alerts.map(alert=><button key={alert.id} className={`attention ${alert.tone}`} onClick={()=>navigate(alert.to)}><span className="attention-icon"><AlertTriangle size={19}/></span><span><em>{alert.eyebrow}</em><strong>{alert.title}</strong><small>{alert.detail}</small></span><ChevronRight size={20}/></button>)}</div></section>
    <div className="two-column"><section className="panel"><div className="section-heading"><h2>Produção por etapa</h2><button className="text-button" onClick={()=>navigate('/producao')}>Ver quadro</button></div><div className="stage-bars">{state.stages.map(stage=>{const count=state.orders.filter(order=>order.stageId===stage.id).length;return <button key={stage.id} onClick={()=>navigate('/producao')}><span>{stage.label}</span><span className="bar"><i style={{width:`${Math.max(count/state.orders.length*100,5)}%`}}/></span><b>{count}</b></button>})}</div><p className="panel-note">Fluxo demonstrativo — as etapas podem ser adaptadas ao processo da empresa.</p></section>
    <section className="panel"><div className="section-heading"><h2>Próximas entregas</h2><button className="text-button" onClick={()=>navigate('/pedidos')}>Todos</button></div><div className="delivery-list">{deliveries.map(order=><button key={order.id} onClick={()=>navigate(`/pedidos/${order.id}`)}><span className={`date-badge ${daysFromNow(order.deadline)<0?'late':''}`}><b>{dayMonth(order.deadline).split('/')[0]}</b><small>{new Intl.DateTimeFormat('pt-BR',{month:'short'}).format(new Date(`${order.deadline}T12:00:00`)).replace('.','')}</small></span><span><strong>#{order.number} · {state.clients.find(c=>c.id===order.clientId)?.companyName}</strong><small>{order.quantity} peças · {state.stages.find(s=>s.id===order.stageId)?.label}</small></span></button>)}</div></section></div>
  </>;
}

function Orders() {
  const {state}=useStore(); const [search,setSearch]=useState(''); const [stage,setStage]=useState(''); const [priority,setPriority]=useState(''); const navigate=useNavigate();
  const list=state.orders.filter(order=>{const client=state.clients.find(c=>c.id===order.clientId)?.companyName??''; return `${order.number} ${client} ${order.product}`.toLowerCase().includes(search.toLowerCase()) && (!stage||order.stageId===stage)&&(!priority||order.priority===priority)}).sort((a,b)=>a.deadline.localeCompare(b.deadline));
  return <><PageHeader eyebrow="Operação" title="Pedidos" description={`${list.length} pedidos encontrados`} action={<button className="button primary" onClick={()=>navigate('/pedidos/novo')}><PackagePlus size={17}/>Novo pedido</button>}/><div className="filters"><label className="search"><Search size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar pedido, cliente ou produto"/></label><select value={stage} onChange={e=>setStage(e.target.value)} aria-label="Filtrar por etapa"><option value="">Todas as etapas</option>{state.stages.map(item=><option key={item.id} value={item.id}>{item.label}</option>)}</select><select value={priority} onChange={e=>setPriority(e.target.value)} aria-label="Filtrar por prioridade"><option value="">Todas as prioridades</option>{['urgente','alta','normal','baixa'].map(item=><option key={item}>{labelStatus(item)}</option>)}</select></div>
    {list.length===0?<Empty title="Nenhum pedido encontrado" detail="Ajuste os filtros para voltar a ver a operação."/>:<div className="table-wrap"><table><thead><tr><th>Pedido</th><th>Cliente e produto</th><th>Peças</th><th>Prazo</th><th>Etapa</th><th>Progresso</th><th></th></tr></thead><tbody>{list.map(order=><tr key={order.id} onClick={()=>navigate(`/pedidos/${order.id}`)}><td><strong>#{order.number}</strong><small className={`priority ${order.priority}`}>{labelStatus(order.priority)}</small></td><td><strong>{state.clients.find(c=>c.id===order.clientId)?.companyName}</strong><small>{order.product}</small></td><td>{order.quantity}</td><td><strong className={daysFromNow(order.deadline)<0?'danger-text':''}>{shortDate(order.deadline)}</strong><small>{daysFromNow(order.deadline)<0?'Atrasado':daysFromNow(order.deadline)===0?'Hoje':`em ${daysFromNow(order.deadline)} dias`}</small></td><td><StageChip order={order}/></td><td><div className="progress"><span style={{width:`${orderProgress(state,order)}%`}}/></div><small>{orderProgress(state,order)}%</small></td><td><ChevronRight size={18}/></td></tr>)}</tbody></table></div>}
  </>;
}

function NewOrder() {
  const {state,dispatch}=useStore(); const {notify}=useShell(); const navigate=useNavigate(); const tomorrow=new Date();tomorrow.setDate(tomorrow.getDate()+14);
  const [form,setForm]=useState({clientId:state.clients[0].id,product:'Camiseta personalizada',quantity:50,deadline:tomorrow.toISOString().slice(0,10),amount:4500,responsibleId:state.responsibles[0].id,priority:'normal' as Priority,color:'Azul-marinho',technicalNotes:''});
  const [error,setError]=useState(''); const sizeGrid:SizeRow[]=[{color:form.color,P:5,M:15,G:17,GG:9,XG:4}];
  const submit=(e:FormEvent)=>{e.preventDefault();if(sizeGrid[0].P+sizeGrid[0].M+sizeGrid[0].G+sizeGrid[0].GG+sizeGrid[0].XG!==Number(form.quantity)){setError('A grade precisa somar a quantidade do pedido.');return;}dispatch({type:'ADD_ORDER',payload:{...form,colors:[form.color],sizeGrid,quantity:Number(form.quantity),amount:Number(form.amount)}});notify('Pedido criado e adicionado à produção.');navigate('/pedidos')};
  return <><PageHeader eyebrow="Novo pedido" title="Registrar pedido" description="Dados mínimos para inserir o trabalho no fluxo demonstrativo."/><form className="form-panel" onSubmit={submit}><div className="form-grid"><Field label="Cliente"><select value={form.clientId} onChange={e=>setForm({...form,clientId:e.target.value})}>{state.clients.map(c=><option key={c.id} value={c.id}>{c.companyName}</option>)}</select></Field><Field label="Produto"><input required value={form.product} onChange={e=>setForm({...form,product:e.target.value})}/></Field><Field label="Quantidade"><input type="number" min="1" value={form.quantity} onChange={e=>setForm({...form,quantity:Number(e.target.value)})}/></Field><Field label="Cor"><input value={form.color} onChange={e=>setForm({...form,color:e.target.value})}/></Field><Field label="Prazo"><input type="date" value={form.deadline} onChange={e=>setForm({...form,deadline:e.target.value})}/></Field><Field label="Valor"><input type="number" min="0" value={form.amount} onChange={e=>setForm({...form,amount:Number(e.target.value)})}/></Field><Field label="Responsável"><select value={form.responsibleId} onChange={e=>setForm({...form,responsibleId:e.target.value})}>{state.responsibles.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></Field><Field label="Prioridade"><select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value as Priority})}>{['normal','alta','urgente','baixa'].map(p=><option key={p}>{p}</option>)}</select></Field></div><div className="grade-editor"><h2>Grade COR × TAMANHO</h2><p>Distribuição inicial para 50 peças. Ajuste a quantidade do pedido para 50 nesta versão compacta do cadastro.</p><SizeGrid grid={sizeGrid}/><strong>Total: {gridTotal(sizeGrid)} peças</strong></div><Field label="Observações técnicas"><textarea value={form.technicalNotes} onChange={e=>setForm({...form,technicalNotes:e.target.value})}/></Field>{error&&<div className="form-error">{error}</div>}<div className="actions"><button type="button" className="button ghost" onClick={()=>navigate('/pedidos')}>Cancelar</button><button className="button primary">Salvar pedido</button></div></form></>;
}

function OrderDetail() {
  const {id}=useParams(); const {state,dispatch}=useStore(); const {notify}=useShell(); const navigate=useNavigate(); const order=state.orders.find(item=>item.id===id);
  if(!order)return <NotFound/>; const client=state.clients.find(c=>c.id===order.clientId)!; const stage=state.stages.find(s=>s.id===order.stageId)!; const balance=order.amount-order.receivedAmount;
  const copy=async()=>{const message=`Olá! Seu pedido #${order.number} avançou para a etapa de ${stage.label} e continua previsto para entrega em ${dayMonth(order.deadline)}.`;try{await navigator.clipboard.writeText(message)}catch{const area=document.createElement('textarea');area.value=message;document.body.append(area);area.select();document.execCommand('copy');area.remove()}notify('Mensagem copiada.')};
  return <><button className="back" onClick={()=>navigate(-1)}><ArrowLeft size={17}/>Voltar</button><PageHeader eyebrow={`Pedido #${order.number}`} title={order.product} description={`${client.companyName} · ${order.quantity} peças`} action={<div className="actions"><button className="button secondary" onClick={copy}><Clipboard size={17}/>Copiar atualização</button><select className="button-select" value={order.stageId} onChange={e=>{dispatch({type:'MOVE_ORDER',orderId:order.id,stageId:e.target.value});notify('Etapa do pedido atualizada.')}} aria-label="Mover pedido para etapa">{state.stages.map(item=><option value={item.id} key={item.id}>Mover para {item.label}</option>)}</select></div>}/><div className="detail-strip"><div><span>Prazo</span><strong className={daysFromNow(order.deadline)<0?'danger-text':''}>{shortDate(order.deadline)}</strong></div><div><span>Etapa atual</span><strong>{stage.label}</strong></div><div><span>Responsável</span><strong>{state.responsibles.find(r=>r.id===order.responsibleId)?.name}</strong></div><div><span>Valor</span><strong>{money(order.amount)}</strong></div></div>
    <div className="detail-grid"><section className="panel span-2"><div className="section-heading"><div><span className="eyebrow">Produto</span><h2>Grade de produção</h2></div><span className="priority alta">{order.quantity} peças</span></div><p>{order.technicalNotes}</p><SizeGrid grid={order.sizeGrid}/></section><section className="panel"><span className="eyebrow">Contato</span><h2>{client.companyName}</h2><p>{client.contactName}<br/>{client.phone}<br/>{client.city}</p></section>
    <section className="panel"><span className="eyebrow">Arte</span><h2>Versões e aprovação</h2>{order.artworkVersions.length?order.artworkVersions.map(art=><div className="art-card" key={art.id}><div className="art-preview">{art.colors.map(c=><span key={c} style={{background:c}}/>)}</div><div><strong>{art.version} · {labelStatus(art.status)}</strong><small>{shortDate(art.createdAt)} · {art.note}</small></div></div>):<p className="muted">A arte ainda não foi anexada nesta demonstração.</p>}</section>
    <section className="panel"><span className="eyebrow">Materiais</span><h2>Necessidades vinculadas</h2>{order.materialNeeds.map(need=>{const material=state.materials.find(m=>m.id===need.materialId)!;return <div className="material-need" key={material.id}><strong>{material.name}</strong><span>Necessário: {need.required} {material.unit}</span><span>Alocado: {need.allocated} {material.unit}</span>{need.required>need.allocated&&<em>Faltam {need.required-need.allocated} {material.unit}</em>}</div>})}</section>
    <section className="panel"><span className="eyebrow">Financeiro resumido</span><h2>{money(balance)} em aberto</h2><dl className="facts"><div><dt>Total</dt><dd>{money(order.amount)}</dd></div><div><dt>Recebido</dt><dd>{money(order.receivedAmount)}</dd></div><div><dt>Condição</dt><dd>{order.paymentTerms}</dd></div></dl></section>
    <section className="panel span-2"><span className="eyebrow">Histórico</span><h2>Últimas movimentações</h2><div className="timeline">{[...order.history].reverse().map(item=><div key={item.id}><i/><span><strong>{item.label}</strong><small>{new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(new Date(item.timestamp))}</small></span></div>)}</div></section></div>
  </>;
}

function SizeGrid({grid}:{grid:SizeRow[]}) { return <div className="size-grid"><table><thead><tr><th>Cor</th>{sizes.map(s=><th key={s}>{s}</th>)}<th>Total</th></tr></thead><tbody>{grid.map(row=><tr key={row.color}><td>{row.color}</td>{sizes.map(s=><td key={s}>{row[s]}</td>)}<td><strong>{sizes.reduce((sum,s)=>sum+row[s],0)}</strong></td></tr>)}</tbody><tfoot><tr><td>Total</td>{sizes.map(s=><td key={s}>{grid.reduce((sum,row)=>sum+row[s],0)}</td>)}<td>{gridTotal(grid)}</td></tr></tfoot></table></div> }

function Production() {
  const {state,dispatch}=useStore();const {notify}=useShell();
  return <><PageHeader eyebrow="Chão de fábrica" title="Produção" description="Fluxo demonstrativo — etapas, responsáveis e regras podem ser adaptados."/><div className="kanban">{state.stages.map(stage=><section className="kanban-column" key={stage.id}><header><span>{stage.label}</span><b>{state.orders.filter(o=>o.stageId===stage.id).length}</b></header><div>{state.orders.filter(o=>o.stageId===stage.id).map(order=><article className="kanban-card" key={order.id}><NavLink to={`/pedidos/${order.id}`}><span className="eyebrow">#{order.number}</span><strong>{state.clients.find(c=>c.id===order.clientId)?.companyName}</strong><p>{order.product}</p><div><span>{order.quantity} peças</span><span className={daysFromNow(order.deadline)<0?'danger-text':''}>{dayMonth(order.deadline)}</span></div></NavLink><label><span className="sr-only">Mover pedido #{order.number}</span><select value={order.stageId} onChange={e=>{dispatch({type:'MOVE_ORDER',orderId:order.id,stageId:e.target.value});notify(`Pedido #${order.number} movido.`)}}>{state.stages.map(item=><option key={item.id} value={item.id}>{item.label}</option>)}</select></label></article>)}</div></section>)}</div></>;
}

function Quotes() {
  const {state}=useStore();const navigate=useNavigate();
  return <><PageHeader eyebrow="Fluxo comercial" title="Orçamentos" description="Do envio à aprovação e conversão em pedido." action={<button className="button primary" onClick={()=>navigate('/orcamentos/novo')}><FileText size={17}/>Novo orçamento</button>}/><div className="quote-grid">{state.quotes.map(quote=><button className="quote-card" key={quote.id} onClick={()=>navigate(`/orcamentos/${quote.id}`)}><div><span className="eyebrow">Orçamento #{quote.number}</span><span className={`status ${quote.status.replaceAll(' ','-')}`}>{labelStatus(quote.status)}</span></div><h2>{state.clients.find(c=>c.id===quote.clientId)?.companyName}</h2><p>{quote.product} · {quote.quantity} peças</p><footer><strong>{money(quote.amount)}</strong><span>Válido até {dayMonth(quote.validUntil)}</span><ChevronRight size={18}/></footer></button>)}</div></>;
}

function NewQuote() {
  const {state,dispatch}=useStore();const {notify}=useShell();const navigate=useNavigate();const valid=new Date();valid.setDate(valid.getDate()+7);const delivery=new Date();delivery.setDate(delivery.getDate()+18);
  const [form,setForm]=useState({clientId:state.clients[0].id,product:'Camiseta personalizada',validUntil:valid.toISOString().slice(0,10),estimatedDeadline:delivery.toISOString().slice(0,10),amount:7200,color:'Azul-marinho',customization:'Estampa frontal em duas cores',notes:'Condições fictícias para demonstração.'});
  const sizeGrid:SizeRow[]=[{color:form.color,P:11,M:24,G:25,GG:14,XG:6}];
  const submit=(event:FormEvent)=>{event.preventDefault();dispatch({type:'ADD_QUOTE',payload:{...form,quantity:80,colors:[form.color],sizeGrid}});notify('Orçamento salvo como rascunho.');navigate('/orcamentos')};
  return <><PageHeader eyebrow="Novo orçamento" title="Preparar proposta demonstrativa" description="Cadastro funcional com grade, personalização, prazo e valor."/><form className="form-panel" onSubmit={submit}><div className="form-grid"><Field label="Cliente"><select value={form.clientId} onChange={e=>setForm({...form,clientId:e.target.value})}>{state.clients.map(client=><option key={client.id} value={client.id}>{client.companyName}</option>)}</select></Field><Field label="Produto"><input required value={form.product} onChange={e=>setForm({...form,product:e.target.value})}/></Field><Field label="Cor"><input required value={form.color} onChange={e=>setForm({...form,color:e.target.value})}/></Field><Field label="Valor demonstrativo"><input type="number" min="0" value={form.amount} onChange={e=>setForm({...form,amount:Number(e.target.value)})}/></Field><Field label="Validade"><input type="date" value={form.validUntil} onChange={e=>setForm({...form,validUntil:e.target.value})}/></Field><Field label="Entrega estimada"><input type="date" value={form.estimatedDeadline} onChange={e=>setForm({...form,estimatedDeadline:e.target.value})}/></Field></div><div className="grade-editor"><h2>Grade proposta · 80 peças</h2><SizeGrid grid={sizeGrid}/></div><Field label="Personalização"><textarea value={form.customization} onChange={e=>setForm({...form,customization:e.target.value})}/></Field><Field label="Observações"><textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></Field><div className="actions"><button type="button" className="button ghost" onClick={()=>navigate('/orcamentos')}>Cancelar</button><button className="button primary">Salvar rascunho</button></div></form></>;
}

function QuoteDetail() {
  const {id}=useParams();const {state,dispatch}=useStore();const {notify}=useShell();const navigate=useNavigate();const quote=state.quotes.find(q=>q.id===id);if(!quote)return <NotFound/>;const client=state.clients.find(c=>c.id===quote.clientId)!;
  return <><button className="back" onClick={()=>navigate('/orcamentos')}><ArrowLeft size={17}/>Orçamentos</button><PageHeader eyebrow={`Orçamento #${quote.number}`} title={quote.product} description={`${client.companyName} · ${quote.quantity} peças`} action={<div className="actions"><button className="button secondary" onClick={()=>navigate(`/cliente/orcamento/${quote.id}`)}>Abrir portal do cliente</button>{quote.status==='aprovado'&&<button className="button primary" onClick={()=>{dispatch({type:'CONVERT_QUOTE',quoteId:quote.id});notify('Orçamento transformado em pedido.')}}>Transformar em pedido</button>}</div>}/><div className="detail-strip"><div><span>Status</span><strong>{labelStatus(quote.status)}</strong></div><div><span>Validade</span><strong>{shortDate(quote.validUntil)}</strong></div><div><span>Entrega estimada</span><strong>{shortDate(quote.estimatedDeadline)}</strong></div><div><span>Valor</span><strong>{money(quote.amount)}</strong></div></div><div className="detail-grid"><section className="panel span-2"><h2>Grade proposta</h2><SizeGrid grid={quote.sizeGrid}/></section><section className="panel"><h2>Personalização</h2><p>{quote.customization}</p><p className="muted">{quote.notes}</p></section><section className="panel"><h2>Retorno do cliente</h2>{quote.customerChangeRequest?<div className="callout warning">{quote.customerChangeRequest}</div>:<p className="muted">Nenhuma observação registrada.</p>}{quote.convertedOrderId&&<button className="text-button" onClick={()=>navigate(`/pedidos/${quote.convertedOrderId}`)}>Abrir pedido criado →</button>}</section></div></>;
}

function CustomerPortal() {
  const {id}=useParams();const {state,dispatch}=useStore();const {notify}=useShell();const quote=state.quotes.find(q=>q.id===id);const [change,setChange]=useState(false);const [note,setNote]=useState('');if(!quote)return <NotFound/>;const client=state.clients.find(c=>c.id===quote.clientId)!;
  return <main className="portal"><header><div className="brand"><span className="brand-mark">{state.config.logoText}</span><div><strong>{state.config.companyName}</strong><small>Portal demonstrativo de aprovação</small></div></div><span className="demo-pill">Ambiente demonstrativo • dados fictícios</span></header><section className="portal-card"><span className="eyebrow">Orçamento #{quote.number}</span><h1>Olá, {client.contactName.split(' ')[0]}.</h1><p>Revise abaixo a proposta fictícia preparada para {client.companyName}.</p><div className="portal-summary"><div><span>Produto</span><strong>{quote.product}</strong></div><div><span>Quantidade</span><strong>{quote.quantity} peças</strong></div><div><span>Prazo estimado</span><strong>{shortDate(quote.estimatedDeadline)}</strong></div><div><span>Valor demonstrativo</span><strong>{money(quote.amount)}</strong></div></div><SizeGrid grid={quote.sizeGrid}/><div className="callout"><strong>Personalização</strong><p>{quote.customization}</p></div>{quote.status==='aprovado'?<div className="portal-success"><Check/>Orçamento aprovado nesta demonstração.</div>:quote.status==='alteração solicitada'?<div className="callout warning"><strong>Alteração solicitada</strong><p>{quote.customerChangeRequest}</p></div>:change?<div className="change-box"><label>O que precisa ser ajustado?<textarea autoFocus value={note} onChange={e=>setNote(e.target.value)} placeholder="Descreva a alteração"/></label><div className="actions"><button className="button ghost" onClick={()=>setChange(false)}>Cancelar</button><button className="button primary" disabled={!note.trim()} onClick={()=>{dispatch({type:'UPDATE_QUOTE',quoteId:quote.id,status:'alteração solicitada',note:note.trim()});notify('Solicitação enviada para a área administrativa.')}}>Enviar solicitação</button></div></div>:<div className="portal-actions"><button className="button ghost" onClick={()=>setChange(true)}>Solicitar alteração</button><button className="button primary" onClick={()=>{dispatch({type:'UPDATE_QUOTE',quoteId:quote.id,status:'aprovado'});notify('Orçamento aprovado.')}}><Check size={18}/>Aprovar orçamento</button></div>}<p className="portal-note">Esta tela demonstra um fluxo possível. O sistema real pode seguir as regras de aprovação da sua empresa.</p></section></main>;
}

function Clients() { const {state}=useStore();const navigate=useNavigate();return <><PageHeader eyebrow="Relacionamento" title="Clientes" description="Visão resumida, derivada dos pedidos e orçamentos."/><div className="client-grid">{state.clients.map(client=>{const stats=clientStats(state,client.id);return <button className="client-card" key={client.id} onClick={()=>navigate(`/clientes/${client.id}`)}><span className="avatar">{client.companyName.split(' ').slice(0,2).map(s=>s[0]).join('')}</span><span><h2>{client.companyName}</h2><p>{client.contactName} · {client.city}</p><small>{stats.orders} pedidos · {money(stats.amount)} movimentados</small></span><ChevronRight/></button>})}</div></> }
function ClientDetail() { const {id}=useParams();const {state}=useStore();const navigate=useNavigate();const client=state.clients.find(c=>c.id===id);if(!client)return <NotFound/>;const stats=clientStats(state,client.id);const orders=state.orders.filter(o=>o.clientId===client.id);return <><button className="back" onClick={()=>navigate('/clientes')}><ArrowLeft size={17}/>Clientes</button><PageHeader eyebrow="Cliente fictício" title={client.companyName} description={`${client.contactName} · ${client.city}`}/><div className="detail-strip"><div><span>Pedidos</span><strong>{stats.orders}</strong></div><div><span>Valor movimentado</span><strong>{money(stats.amount)}</strong></div><div><span>Último pedido</span><strong>{stats.lastOrder?shortDate(stats.lastOrder):'—'}</strong></div><div><span>Contato</span><strong>{client.phone}</strong></div></div><section className="panel"><h2>Pedidos relacionados</h2><div className="delivery-list">{orders.map(order=><button key={order.id} onClick={()=>navigate(`/pedidos/${order.id}`)}><span className="avatar">#{order.number}</span><span><strong>{order.product}</strong><small>{order.quantity} peças · {money(order.amount)}</small></span><ChevronRight/></button>)}</div></section></> }
function Inventory() { const {state}=useStore();return <><PageHeader eyebrow="Suprimentos" title="Materiais" description="Saldo demonstrativo relacionado às necessidades dos pedidos."/><div className="table-wrap"><table><thead><tr><th>Código</th><th>Material</th><th>Em estoque</th><th>Reservado</th><th>Disponível</th><th>Mínimo</th><th>Status</th></tr></thead><tbody>{state.materials.map(material=>{const reserved=materialReserved(state,material);const available=material.stockOnHand-reserved;const status=materialStatus(state,material);return <tr key={material.id}><td>{material.code}</td><td><strong>{material.name}</strong><small>{material.category}</small></td><td>{material.stockOnHand} {material.unit}</td><td>{reserved} {material.unit}</td><td className={available<0?'danger-text':''}>{available} {material.unit}</td><td>{material.minimum} {material.unit}</td><td><span className={`stock-status ${status.toLowerCase().replace('í','i').replace('ç','c')}`}>{status}</span></td></tr>})}</tbody></table></div></> }
function Configuration() { const {state,dispatch}=useStore();const {notify}=useShell();const [form,setForm]=useState(state.config);const save=(e:FormEvent)=>{e.preventDefault();dispatch({type:'UPDATE_CONFIG',payload:form});notify('Identidade da demonstração atualizada.')};return <><PageHeader eyebrow="Configurabilidade" title="Ajustes da demonstração" description="No sistema real, etapas, campos e regras podem ser adaptados."/><form className="form-panel" onSubmit={save}><div className="form-grid"><Field label="Nome da demonstração"><input value={form.companyName} onChange={e=>setForm({...form,companyName:e.target.value})}/></Field><Field label="Sigla"><input maxLength={3} value={form.logoText} onChange={e=>setForm({...form,logoText:e.target.value.toUpperCase()})}/></Field><Field label="Cor principal"><input type="color" value={form.primaryColor} onChange={e=>setForm({...form,primaryColor:e.target.value})}/></Field><Field label="Cidade"><input value={form.city} onChange={e=>setForm({...form,city:e.target.value})}/></Field><Field label="Vendedor"><input value={form.salesperson} onChange={e=>setForm({...form,salesperson:e.target.value})}/></Field></div><div className="actions"><button className="button primary"><Palette size={17}/>Salvar ajustes</button></div></form><section className="panel reset-panel"><div><h2>Restaurar demonstração</h2><p>Remove as alterações locais e recria o conjunto completo de dados com datas relativas a hoje.</p></div><button className="button danger" onClick={()=>{if(window.confirm('Restaurar todos os dados fictícios da demonstração?')){dispatch({type:'RESET'});notify('Demonstração restaurada.')}}}><RotateCcw size={17}/>Restaurar dados</button></section></> }
function Field({label,children}:{label:string;children:React.ReactNode}) { return <label className="field"><span>{label}</span>{children}</label> }
function Empty({title,detail}:{title:string;detail:string}) { return <div className="empty"><Search/><h2>{title}</h2><p>{detail}</p></div> }
function NotFound() { return <div className="empty"><AlertTriangle/><h1>Conteúdo não encontrado</h1><p>Este registro não existe ou foi removido da demonstração.</p><NavLink className="button primary" to="/">Voltar à visão geral</NavLink></div> }
